# Generated by Django 3.1.7 on 2021-07-18 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='timings',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
